server:
  port: 8888
# Oracle Connect
spring:
  #File Size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  file:
    upload:
#      path: C:\spring\project1\jmAuto\src\main\resources\static\images\
      path: C:\Users\admin\Downloads\1016_endendend\jmAuto\src\main\resources\static\images\
      
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: S202430101
    password: tiger
    


  # Jpa Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # logger를 통해 하이버네이트 실행 SQL

  # View Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  mail:
    host: smtp.gmail.com
    port: 587
    username: fantamasitta@gmail.com
    password: btdq swey iild bdzf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#MyBatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    org:
      hibernate:
        SQL: debug
